Feat/portal administration
equinor/fusion-project-portal pull request #710
Opened 2024-08-19 10:16 UTC by Noggling

# Description

- [ ] PR title and description are to the point and understandable
- [ ] I have performed a self-review of my own code'

Please select version type the purposed change:
- [ ] major
- [ ] minor
- [ ] patch
- [ ] none  

External Relations
- [ ] database migration

## Changeset

2024-09-12 10:36 UTC, EdwardBrunton requested changes

2024-09-12 10:36 UTC, EdwardBrunton commented on client/apps/portal-administration/src/components/Router/RouteMenu.tsx
> +	);
Is this used?

2024-09-12 10:36 UTC, EdwardBrunton commented on client/apps/portal-administration/src/components/Router/RouterConfig.tsx
> +}
Could you please add a comment or something to explain what this does?

2024-09-12 10:36 UTC, EdwardBrunton commented on client/apps/portal-administration/src/components/Tree/TreeItem.tsx
> +export const TreeItem = ({
Is it not possible to have root and item be the same object?

2024-09-13 06:03 UTC, Noggling commented on client/apps/portal-administration/src/components/FormComponents/IconInput.tsx
> +								__html: icon.replace(/\s+/g, ' ').trim(),
Its the only what we can do it now :/

2024-09-13 06:04 UTC, Noggling commented on client/apps/portal-administration/src/components/OnboardedApps/AppSelector.tsx
> +const singleItem = (props: unknown): SearchableDropdownResultItem => {
nope used down below, but props are used. its to ensure that we always return an item

2024-09-13 06:06 UTC, Noggling commented on client/apps/portal-administration/src/components/PortalApps/ContextAppSideSheet.tsx
> +					<Button>Activate apps with selected contexts</Button>
This file / feature is wip and is relying on some backend changes. will be fully implemented in teh next pr

2024-09-13 08:04 UTC, EdwardBrunton approved these changes

2024-09-13 11:45 UTC, merged